=== ForensicBioinformatics/osiris/osiris/OsirisXML/MarkovProcess.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp2 (http://www.altova.com) by Robert Goor (National Library of Medicine) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="MarkovProcess">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="MarkovState"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MarkovState">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Value" type="xs:int"/>
				<xs:sequence maxOccurs="unbounded">
					<xs:element ref="MarkovTransition"/>
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MarkovTransition">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ToState" type="xs:int"/>
				<xs:element name="Frequency" type="xs:double"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ForensicBioinformatics/osiris/osiris/OsirisXML/MarkovProperties.xml
<?xml version="1.0" encoding="UTF-8"?>
<MarkovProcess xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E:\Users\goorrob\My Documents\DEV\internal\osiris\OsirisXML\MarkovProcess.xsd">
	<MarkovState>
		<Value>0</Value>
		<MarkovTransition>
			<ToState>0</ToState>
			<Frequency>22.</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>1</ToState>
			<Frequency>10</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>2</ToState>
			<Frequency>2</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>-1</ToState>
			<Frequency>5</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>-2</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>1</Value>
		<MarkovTransition>
			<ToState>1</ToState>
			<Frequency>6</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>2</ToState>
			<Frequency>13</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>3</ToState>
			<Frequency>3</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>4</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>0</ToState>
			<Frequency>9</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>-1</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>2</Value>
		<MarkovTransition>
			<ToState>2</ToState>
			<Frequency>12</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>3</ToState>
			<Frequency>14</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>4</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>5</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>1</ToState>
			<Frequency>10</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>0</ToState>
			<Frequency>2</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>3</Value>
		<MarkovTransition>
			<ToState>3</ToState>
			<Frequency>20</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>4</ToState>
			<Frequency>12</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>5</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>6</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>2</ToState>
			<Frequency>11</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>1</ToState>
			<Frequency>3</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>0</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>4</Value>
		<MarkovTransition>
			<ToState>4</ToState>
			<Frequency>14</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>5</ToState>
			<Frequency>12</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>6</ToState>
			<Frequency>3</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>3</ToState>
			<Frequency>12</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>2</ToState>
			<Frequency>2</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>5</Value>
		<MarkovTransition>
			<ToState>5</ToState>
			<Frequency>12</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>6</ToState>
			<Frequency>7</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>7</ToState>
			<Frequency>2</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>4</ToState>
			<Frequency>11</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>3</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>2</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>6</Value>
		<MarkovTransition>
			<ToState>6</ToState>
			<Frequency>4</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>7</ToState>
			<Frequency>4</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>8</ToState>
			<Frequency>4</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>5</ToState>
			<Frequency>7</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>4</ToState>
			<Frequency>5</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>7</Value>
		<MarkovTransition>
			<ToState>7</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>8</ToState>
			<Frequency>2</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>9</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>6</ToState>
			<Frequency>8</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>5</ToState>
			<Frequency>2</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>8</Value>
		<MarkovTransition>
			<ToState>8</ToState>
			<Frequency>4</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>9</ToState>
			<Frequency>2</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>10</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>7</ToState>
			<Frequency>6</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>6</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>9</Value>
		<MarkovTransition>
			<ToState>9</ToState>
			<Frequency>2</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>10</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>8</ToState>
			<Frequency>4</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>10</Value>
		<MarkovTransition>
			<ToState>10</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>11</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>9</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>11</Value>
		<MarkovTransition>
			<ToState>12</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>10</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>12</Value>
		<MarkovTransition>
			<ToState>11</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>-1</Value>
		<MarkovTransition>
			<ToState>-1</ToState>
			<Frequency>2</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>0</ToState>
			<Frequency>5</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>1</ToState>
			<Frequency>2</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>-2</ToState>
			<Frequency>3</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>-2</Value>
		<MarkovTransition>
			<ToState>-2</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>-1</ToState>
			<Frequency>2</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>0</ToState>
			<Frequency>1</Frequency>
		</MarkovTransition>
		<MarkovTransition>
			<ToState>-3</ToState>
			<Frequency>2</Frequency>
		</MarkovTransition>
	</MarkovState>
	<MarkovState>
		<Value>-3</Value>
		<MarkovTransition>
			<ToState>-2</ToState>
			<Frequency>2</Frequency>
		</MarkovTransition>
	</MarkovState>
</MarkovProcess>
