=== ForensicBioinformatics/osiris/osiris/MessageBook/OsirisMessageBook2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp2 (http://www.altova.com) by Robert Goor (National Library of Medicine) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="MessageList">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="Message"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="MessageKey">
			<xs:selector xpath=".//Message"/>
			<xs:field xpath="Index"/>
		</xs:key>
	</xs:element>
	<xs:element name="Message">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Index" type="xs:integer"/>
				<xs:element name="Text" type="xs:string" maxOccurs="unbounded"/>
				<xs:element name="NDataElements" default="0" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Subject" type="xs:integer"/>
				<xs:element name="MessageLevel" type="xs:integer"/>
				<xs:element name="Label" type="xs:string" minOccurs="0"/>
				<xs:element name="TriggersLowPrioritySignal" type="xs:boolean" minOccurs="0"/>
				<xs:element name="DoNotCall" type="xs:boolean" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ForensicBioinformatics/osiris/osiris/MessageBook/OsirisMessageBook2.xml
<?xml version="1.0" encoding="UTF-8"?>
<MessageList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="OsirisMessageBook2.xsd">
	<Message>
		<Index>0</Index>
		<Text>SAMPLE COULD NOT BE ANALYZED</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>1</Index>
		<Text>POSITIVE CONTROL LOCUS MISMATCH</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>2</Index>
		<Text>NEGATIVE CONTROL REQUIRES ANALYST REVIEW</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>3</Index>
		<Text>ILS COULD NOT BE ANALYZED</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>4</Index>
		<Text>ALLELIC LADDER COULD NOT BE ANALYZED</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>90</Index>
		<Text>ILS SPACING DOES NOT MEET EXPECTED PARAMETERS</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>91</Index>
		<Text>LOCUS SPACING DOES NOT MEET EXPECTED PARAMETERS</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>100</Index>
		<Text>NO ALLELIC LADDER FILE IDENTIFIED</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>101</Index>
		<Text>THE ALLELIC LADDER TYPE IS NOT RECOGNIZED</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>104</Index>
		<Text>THE REAGENT KIT IS NOT RECOGNIZED</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>105</Index>
		<Text>MORE THAN ONE REAGENT KIT  IS IDENTIFIED IN THE DIRECTORY</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>106</Index>
		<Text>NO POSITIVE CONTROL SAMPLE WAS FOUND IN THE DIRECTORY</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>107</Index>
		<Text>NO NEGATIVE CONTROL FILE WAS FOUND IN THE DIRECTORY</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>108</Index>
		<Text>NO SAMPLE WAS FOUND IN THE DIRECTORY</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>301</Index>
		<Text>CURVE FIT DOES NOT MEET EXPECTED VALUES</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
		<Label>Curve fit unacceptable</Label>
	</Message>
	<Message>
		<Index>302</Index>
		<Text>CURVE FIT ONLY MARGINALLY MEETS EXPECTED VALUES</Text>
		<Subject>10</Subject>
		<MessageLevel>20</MessageLevel>
		<Label>Curve fit marginal</Label>
	</Message>
	<Message>
		<Index>303</Index>
		<Text> ARTIFACT  FOUND</Text>
		<Subject>10</Subject>
		<MessageLevel>10</MessageLevel>
	</Message>
	<Message>
		<Index>304</Index>
		<Text>ARTIFACT FOUND:  SPIKE</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
		<Label>Spike</Label>
	</Message>
	<Message>
		<Index>305</Index>
		<Text>ARTIFACT  FOUND:  STUTTER</Text>
		<Subject>15</Subject>
		<MessageLevel>20</MessageLevel>
		<Label>Stutter</Label>
		<TriggersLowPrioritySignal>true</TriggersLowPrioritySignal>
		<DoNotCall>true</DoNotCall>
	</Message>
	<Message>
		<Index>306</Index>
		<Text>ARTIFACT  FOUND:  ADENYLATION</Text>
		<Subject>15</Subject>
		<MessageLevel>20</MessageLevel>
		<Label>Adenylation</Label>
		<TriggersLowPrioritySignal>true</TriggersLowPrioritySignal>
		<DoNotCall>true</DoNotCall>
	</Message>
	<Message>
		<Index>307</Index>
		<Text>ARTIFACT  FOUND:  BLOB</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
		<Label>Blob</Label>
	</Message>
	<Message>
		<Index>308</Index>
		<Text>ARTIFACT  FOUND:  PULL-UP</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
		<Label>Pull-up</Label>
	</Message>
	<Message>
		<Index>310</Index>
		<Text>NO GENOTYPE WAS IDENTIFIED</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
		<Label>No Genotype</Label>
	</Message>
	<Message>
		<Index>311</Index>
		<Text>THREE OR MORE ALLELES WERE IDENTIFIED</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
		<Label>Tri-allele</Label>
	</Message>
	<Message>
		<Index>312</Index>
		<Text>UNEXPECTED NUMBER OF PEAKS</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>324</Index>
		<Text>PEAK DETECTED BETWEEN LOCI</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
		<Label>Inter-locus Peak</Label>
	</Message>
	<Message>
		<Index>326</Index>
		<Text>HETEROZYGOUS IMBALANCE DETECTED</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
		<Label>Heterozygous Imbalance</Label>
	</Message>
	<Message>
		<Index>330</Index>
		<Text>OFF LADDER ALLELE(S) DETECTED:</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
		<Label>Off Ladder Allele</Label>
	</Message>
	<Message>
		<Index>356</Index>
		<Text>SINGLE PEAK DETECTED; HEIGHT INAPPROPRIATE FOR HOMOZYGOTE</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
		<Label>Height Inappropriate for Homozygote</Label>
	</Message>
	<Message>
		<Index>359</Index>
		<Text>OSIRIS GENOTYPE DIFFERS FROM ABI GENOTYPE</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>501</Index>
		<Text>ILS CONTAINS TOO FEW PEAKS</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>502</Index>
		<Text>LOCUS CONTAINS TOO FEW PEAKS</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
		<Label>Too Few Peaks</Label>
	</Message>
	<Message>
		<Index>520</Index>
		<Text>DIRECTORY INFORMATION ON SAMPLE DOES NOT MEET EXPECTATIONS</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>701</Index>
		<Text>UNABLE TO READ FSA FILE</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>702</Index>
		<Text>UNABLE TO OPEN INPUT DIRECTORY</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>703</Index>
		<Text>UNABLE TO OPEN OUTPUT FILE</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>704</Index>
		<Text>LADDER DATA FORMAT UNRECOGNIZED</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>705</Index>
		<Text>PERVASIVE STUTTER</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>706</Index>
		<Text>PEAK OUTSIDE ILS RANGE</Text>
		<Subject>20</Subject>
		<MessageLevel>20</MessageLevel>
		<Label>Outside ILS Range</Label>
	</Message>
	<Message>
		<Index>707</Index>
		<Text>FOUND INTER-LOCUS LADDER PEAK</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
		<Label>Interlocus Ladder Peak</Label>
	</Message>
	<Message>
		<Index>708</Index>
		<Text>COULD NOT FIND POPULATION MARKER SET NAMED: </Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>709</Index>
		<Text>COULD NOT FIND INTERNAL LANE STANDARD NAMED: </Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
	</Message>
	<Message>
		<Index>710</Index>
		<Text>SIGNAL TOO LOW FOR LOCUS</Text>
		<Subject>3</Subject>
		<MessageLevel>20</MessageLevel>
		<Label>Too Low for Locus</Label>
		<DoNotCall>true</DoNotCall>
	</Message>
	<Message>
		<Index>711</Index>
		<Text>SIGNAL PEAK BELOW MINIMUM RFU</Text>
		<Subject>1</Subject>
		<MessageLevel>20</MessageLevel>
		<Label>Below Min RFU</Label>
		<DoNotCall>true</DoNotCall>
	</Message>
	<Message>
		<Index>712</Index>
		<Text>UNEXPECTED PEAK IN ILS</Text>
		<Subject>1</Subject>
		<MessageLevel>20</MessageLevel>
		<Label>Unexpected Peak in ILS</Label>
	</Message>
	<Message>
		<Index>713</Index>
		<Text>UNEXPECTED PEAK IN LADDER LOCUS</Text>
		<Subject>1</Subject>
		<MessageLevel>1</MessageLevel>
		<Label>Unexpected Peak in Ladder Locus</Label>
	</Message>
	<Message>
		<Index>714</Index>
		<Text>ARTIFACT  FOUND:  PRIMARY PULL-UP</Text>
		<Subject>1</Subject>
		<MessageLevel>20</MessageLevel>
		<Label>Primary Pull-up</Label>
	</Message>
	<Message>
		<Index>715</Index>
		<Text>POSSIBLE PULL-UP COINCIDES WITH ALLELE</Text>
		<Subject>20</Subject>
		<MessageLevel>20</MessageLevel>
		<Label>Pull-up at Allele</Label>
	</Message>
	<Message>
		<Index>716</Index>
		<Text>POSSIBLE PULL-UP MAY MITIGATE APPARENT HETEROZYGOUS IMBALANCE</Text>
		<Subject>20</Subject>
		<MessageLevel>20</MessageLevel>
		<Label>Pull-up with Heterozygous Imbalance</Label>
	</Message>
	<Message>
		<Index>717</Index>
		<Text>LOW TRI-ALLELE POSSIBLE RESULT OF PULL-UP</Text>
		<Subject>20</Subject>
		<MessageLevel>20</MessageLevel>
		<Label>Low Tri-allele with Pull-up</Label>
	</Message>
	<Message>
		<Index>718</Index>
		<Text>LOW OFF LADDER ALLELE POSSIBLE RESULT OF PULL-UP</Text>
		<Subject>20</Subject>
		<MessageLevel>10</MessageLevel>
		<Label>Low OL Allele with Pull-up</Label>
	</Message>
	<Message>
		<Index>719</Index>
		<Text>POSSIBLE PULL-UP MAY MITIGATE PEAK HEIGHTS OUT OF ORDER</Text>
		<Subject>20</Subject>
		<MessageLevel>20</MessageLevel>
		<Label>Peak Heights Unexpected with Pull-up</Label>
	</Message>
	<Message>
		<Index>720</Index>
		<Text>CALL IGNORES ONE OR MORE LOW OFF-LADDER ALLELES</Text>
		<Subject>20</Subject>
		<MessageLevel>10</MessageLevel>
		<Label>Low Off Ladder Alleles</Label>
	</Message>
	<Message>
		<Index>721</Index>
		<Text>ALLELE PEAK HEIGHTS OUT OF ORDER</Text>
		<Subject>6</Subject>
		<MessageLevel>6</MessageLevel>
		<Label>Peak Heights Unexpected</Label>
	</Message>
	<Message>
		<Index>722</Index>
		<Text>POSSIBLE PULL-UP COINCIDES WITH CONTROL (ILS OR LADDER) PEAK</Text>
		<Subject>20</Subject>
		<MessageLevel>20</MessageLevel>
		<Label>Pull-up at Control Peak</Label>
	</Message>
	<Message>
		<Index>723</Index>
		<Text>POSSIBLE PULL-UP COINCIDES WITH OFF-LADDER ALLELE BETWEEN LOCI</Text>
		<Subject>20</Subject>
		<MessageLevel>20</MessageLevel>
